source 'https://github.com/meliguangjian/lgj-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ConvenientLoginDemo.xcodeproj'

target 'ConvenientLoginDemo' do
    
    pod 'TYAlertController'
    
    pod 'Reachability'

	pod 'MBProgressHUD', '~> 0.9.1'

	pod 'APLKeyboardControls'
    
    pod 'ConvenientLogin'
    pod 'ConvenientLogin/Connection/WeChatSDK'
    
end
